version: 2
jobs:
  build:
    docker:
      - image: cypress/base:8
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache: #Download and cache dependencies
          keys:
            - v1-dependencies-npm-{{ checksum "package-lock.json" }}
            - v1-dependencies-npm

      - run: npm install

      - save_cache:
          key: v1-dependencies-npm-{{ checksum "package-lock.json" }}
          paths:
            - node_modules/

      # run tests!
      - run: mv config/bim.env.js.test config/bim.env.js
      - run: npm start && wait-on http://localhost:8080 && npm run cypress:run