version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/node:10
    working_directory: /home/circleci/repo

  restore_repo: &restore_repo
    restore_cache:
      keys:
        - repo-{{ .Branch }}-{{ .Revision }}


jobs:
  checkout_code:
    <<: *container_config
    steps:
      - *restore_repo
      - checkout
      - save_cache:
          key: repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - .

  test:
    <<: *container_config

    steps:
      - *restore_repo
      - restore_cache: #Download and cache dependencies
          keys:
            - v3-dependencies-npm-{{ checksum "package-lock.json" }}
            - v3-dependencies-npm

      - run: npm ci

      - run: npm run unit
      - run: npm run e2e

      - save_cache:
          key: v3-dependencies-npm-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache

  deploy:
    <<: *container_config
    steps:
      - *restore_repo
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.09.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: push to docker hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t bimdata/platform:latest .
            docker push bimdata/platform:latest

            # deploy master branch
            docker pull bimdata/deployment:latest
            docker run -it bimdata/deployment:latest ansible-playbook -i inventories/staging deploy.yml --tags=platform --extra-vars "ansible_ssh_private_key_file=./files/deploy_rsa" --user=deploy


workflows:
  version: 2
  test_and_deploy:
    jobs:
      - checkout_code
      - test:
          requires:
            - checkout_code
      - deploy:
          requires:
            - checkout_code
            - test
          filters:
            branches:
              only:
                - master
